name: Docker Image CI

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write
  id-token: write

env:
  IMAGE_NAME: observatorio_web

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and tag Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/observatorio/${{ env.IMAGE_NAME }}:latest .
      
      - name: Push Docker image to GitHub Container Registry
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/observatorio/${{ env.IMAGE_NAME }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: SSH Deploy to VPS
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker pull ghcr.io/${{ github.repository_owner }}/observatorio/${{ env.IMAGE_NAME }}:latest
            docker stop observatorio-web || true
            docker rm observatorio-web || true
            docker run -d --name observatorio-web \
              --restart unless-stopped \
              -p 80:80 \
              -v /var/www/observatorio/sites/default/files:/var/www/html/sites/default/files \
              ghcr.io/${{ github.repository_owner }}/observatorio/${{ env.IMAGE_NAME }}:latest